Input ← $ eedadn
        $ drvtee
        $ eandsr
        $ raavrd
        $ atevrs
        $ tsrnev
        $ sdttsa
        $ rasrtv
        $ nssdts
        $ ntnada
        $ svetve
        $ tesnvt
        $ vntsnd
        $ vrdear
        $ dvrsen
        $ enarar

Words ← ⊜∘¬∊,"\n"

MostFrequent ← ⊢⊡ ⊗ /↥ . ∵⧻.⊜□+1⊛. ⊏ ⍏ .
LeastFrequent ← ⊢⊡ ⊗ /↧ . ∵⧻.⊜□+1⊛. ⊏ ⍏ .

# Part 1

≡MostFrequent ⍉ Words Input

# Part 2

≡LeastFrequent ⍉ Words Input
