$ 467..114..
$ ...*......
$ ..35..633.
$ ......#...
$ 617*......
$ .....+.58.
$ ..592.....
$ ......755.
$ ...$.*....
$ .664.598..

⊜∘≠,@\n
¬∊,".1234567890"     # 1/0 map of symbol positions
↻¯1_¯1⬚0+↯:¤0+2△.    # Pad around edges with zeroes
≡≡(>0/+♭)◫3_3        # Countable positions
⊙(..∊:"1234567890".) # Digit positions
×+
⊙(⊐/⊂≡(□⊜parse))     # Part numbers
/⊐⊂≡(□⊜(>⊃⧻(/+))≠0). # Digit positions
×
/+
